### ISSUE TITLE
Running problem in Python

### ISSUE THREAD

**Issue by gapore** [mirca/lad#4] opened 2018-09-04 02:31 UTC
When I test your functions under Python, I just get the following error message:
![forecast_20180904101037](https://user-images.githubusercontent.com/5591063/45006554-23c59100-b02c-11e8-9e8d-a1b8737d4498.png)
I don't know what's wrong with it since I'm new to Python.Maybe the datatype of B1t and Xt is wrong?Can you help me to solve it?
By the way, can I really get matrix C which comprises a group of vectors computed by the code above?
Thanks for your help! Best wishes!

**Comment by mirca** [comment] 2018-09-04 09:49
@gapore hi, I will investigate that sooner than latter. But, from the error message, it looks like  you can't do ``Xt[:, j]`` when you are not in TF eager mode.

**Comment by mirca** [comment] 2018-09-04 09:51
Oh, yes, what are the types of ``B1t`` and ``Xt``? Note that, to use ``lad``, they don't have to be tensors, they can be ``numpy`` arrays.

**Comment by gapore** [comment] 2018-09-04 10:10
dtype('float64')   shape(4489, 24)  
I've tried both `np.matrix` and `np.array` but still get the error message,and when I do `Xt[:,j]` alone I can get the right variable.

**Comment by mirca** [comment] 2018-09-04 16:21
@gapore I see, thanks! I will investigate that. Meanwhile, note that if you want to get the covariance matrix of the parameters you should pass  the argument ``cov = True`` in the ``lad`` function.

**Comment by mirca** [comment] 2018-09-04 16:28
> By the way, can I really get matrix C which comprises a group of vectors computed by the code above?

Yes, provided that you initialized ``C`` somewhere in your notebook, then you should be able to construct ``C``, no problem!

**Comment by mirca** [comment] 2018-09-04 19:06
Hi @gapore, I can't reproduce the error you presented.

Please, take a look at the following example and see whether you can run it without issues:
```
>>> import numpy as np
>>> import tensorflow as tf

# generate fake data
>>> np.random.seed(1)
>>> true_params = np.array([3, 10])
>>> x = np.linspace(-1, 1, 10000)
>>> y = np.random.laplace(loc=x * true_params[0] + true_params[1], scale=1.)

# estimate the coefficients of an affine model
>>> sess = tf.Session()
>>> X = np.vstack([x, np.ones(len(x))])
>>> coeffs = sess.run(lad(X.T, y))
>>> print(coeffs)

[[ 2.98757656]
 [ 9.99776944]]
```

Thanks!

**Comment by mirca** [comment] 2018-09-08 10:28
@gapore any luck on this?

**Comment by gapore** [comment] 2018-11-04 01:02
```
import numpy as np
import scipy.linalg as linalg
from statsmodels.regression.quantile_regression import QuantReg
import tensorflow as tf
from lad import lad

Y = np.array(q)
Y.shape     #(2328,)

N = len(Y)
L = 24     # int in range(1,N/2)
K = N - L + 1

X = linalg.hankel(Y,np.zeros(K))
X = X[:-K+1,:]

Xt = X.T
_,sig,Vt = linalg.svd(X)
Sig = linalg.diagsvd(sig,L,L)
r = np.linalg.matrix_rank(X)
Vt1 = Vt[:r,:]
Sig1 = Sig[:r,:r]
B1 = np.dot(Sig1,Vt1)
B1t = B1.T

# LAD using Quantreg 
C = np.zeros((r,L))        
for j in range(L):
    y = Xt[:,j]
    mod = QuantReg(y,B1t)
    res = mod.fit(q = .5)
    C[:,j] = np.array(res.history['params'][0])

# LAD using lad
D = np.zeros((r,L))      
for j in range(L):
    Coeffs = lad(B1t,Xt[:,j])
    sess = tf.Session()
    temp = sess.run(Coeffs)
    D[:,j] = [temp[k] for k in range(r)]
```

**Comment by gapore** [comment] 2018-11-04 01:19
@mirca  sorry for not replying you in time.  Now I can run the code without error, but the efficiency of the two method above is quite different. The QuantReg method only takes about 550ms  and the lad method takes about 8s.

**Comment by mirca** [comment] 2018-11-05 11:16
@gapore interesting!! do they return the same results?

**Comment by gapore** [comment] 2018-11-06 01:47
@mirca  the two results are different

**Comment by mirca** [comment] 2018-11-06 16:34
@gapore Could you show how different they are?

**Comment by mirca** [comment] 2018-11-06 16:35
@gapore Oh, and BTW, did you figure out what was causing the error you mentioned previously?

**Comment by gapore** [comment] 2018-11-07 01:43
@mirca  I've tested `E = C - D`, the most value in matrix E are around `e-17` and the rest are zero. I think the error is acceptable?

**Comment by mirca** [comment] 2018-11-19 01:24
@gapore yeah, that value is below most machines precision, so it sounds like the problem is solved then :) I'm gonna go ahead and close this, let me know how things go :)

**Closed as completed by mirca** 2018-11-19 01:24 UTC
